apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-go
  labels:
    app: http-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-go
  template:
    metadata:
      labels:
        app: http-go
    spec:
      containers:
      - name: http-go
        image: whpark70/http-go
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-go
  name: http-go
spec:
  ports:
  - name: http-go 
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-go
  type: NodePort
